version: "3.9"

services:
  mvpv0:
    build:
      context: .
      dockerfile: ./api/MVPv0/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env

  mvpv1:
    build:
      context: .
      dockerfile: ./api/MVPv1/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    volumes:
      - ./data:/ROP/data
