version: "3.9"

services:
  app:
    build:
      context: ./api
      dockerfile: MVPv0/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./api:/app

  solver:
    build:
      context: .
      dockerfile: api/MVPv1/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
