version: "3.9"

services:
  mvpv0:
    build:
      context: .
      dockerfile: ./api/MVPv0/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env

  mvpv1:
    build:
      context: .
      dockerfile: ./api/MVPv1/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    volumes:
      - ./data:/MVPv1/data
  
  mvpv1.2:
    build:
      context: .
      dockerfile: ./api/MVPv1.2/Dockerfile
    ports:
      - "5011:5011"
    env_file:
      - ./.env
    volumes:
      - ./data:/MVPv1.2/data

  mvpv2:
    build:
      context: .
      dockerfile: ./api/MVPv2/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./.env
    volumes:
      - ./data:/MVPv2/data